#!/bin/bash

# -e: 命令失败时立即退出
# -u: 使用未定义变量时报错
set -eu

DOCKERFILE="$PROJECT_BJARNE_DIR/Dockerfile"

#==============================================================================
# SAFE MODE FUNCTIONS
#==============================================================================

# Generate image name from current directory
PROJECT_NAME=$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
IMAGE_NAME="bjarne-${PROJECT_NAME}"

# Detect if project uses safe mode
detect_safe_mode() {
    if [[ -f "$DOCKERFILE" ]]; then
        # Check if Docker is available
        if ! command -v docker &>/dev/null; then
            echo -e "${RED}Error: Docker required for safe mode but not found${NC}"
            exit 1
        fi

        # Check if credentials exist
        if [[ ! -f "$HOME/.claude/.credentials.json" ]]; then
            echo -e "${RED}Error: Claude credentials not found at ~/.claude/.credentials.json${NC}"
            echo -e "Run 'claude' on the host first to authenticate"
            exit 1
        fi

        echo "true"
    fi

    echo "false"
}

# Build Docker image if needed
build_docker_image() {
    local force_rebuild="$1"

    if [[ "$force_rebuild" == "true" ]] || ! docker image inspect "$IMAGE_NAME" &>/dev/null 2>&1; then
        echo -e "${CYAN}Building Docker image: $IMAGE_NAME${NC}"
        docker build -t "$IMAGE_NAME" -f "$DOCKERFILE" . || {
            echo -e "${RED}Docker build failed${NC}"
            exit 1
        }
        echo -e "${GREEN}Image built successfully${NC}"
    else
        echo -e "${CYAN}Using cached image: $IMAGE_NAME${NC}"
    fi
}

# Get appropriate Docker base image for detected tech stack
get_base_image() {
    if [[ -f "package.json" ]]; then
        echo "node:22-bookworm"
    elif [[ -f "requirements.txt" ]] || [[ -f "pyproject.toml" ]]; then
        echo "python:3.12-bookworm"
    elif [[ -f "Cargo.toml" ]]; then
        echo "rust:1-bookworm"
    elif [[ -f "go.mod" ]]; then
        echo "golang:1.23-bookworm"
    elif [[ -f "composer.json" ]]; then
        echo "php:8.4-cli-bookworm"
    elif [[ -f "pubspec.yaml" ]]; then
        echo "dart:stable"
    else
        # Default to Node as it includes npm for Claude Code
        echo "node:22-bookworm"
    fi
}

# Generate Dockerfile for safe mode
generate_dockerfile() {
    local base_image=$(get_base_image)

    mkdir -p "$PROJECT_BJARNE_DIR"

    cat > "$DOCKERFILE" << EOF
# Auto-generated by bjarne init --safe
# Modify as needed, then run: bjarne --rebuild

FROM $base_image

# Install Node.js if not present (needed for Claude Code CLI)
RUN command -v node >/dev/null 2>&1 || { \\
    apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*; \\
}

# Install Claude Code CLI
RUN npm install -g @anthropic-ai/claude-code

# Install common dev tools
RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*

# Create non-root user (Claude Code refuses --dangerously-skip-permissions as root)
# Make home directory world-writable so any UID can write (container is sandboxed anyway)
RUN useradd -m -s /bin/bash bjarne && \\
    mkdir -p /workspace && chown bjarne:bjarne /workspace && \\
    mkdir -p /home/bjarne/.claude && \\
    chmod -R 777 /home/bjarne
USER bjarne

WORKDIR /workspace
EOF

    echo -e "  - Generated $DOCKERFILE (base: $base_image)"
}

# Get volume mount for tech-specific dependencies
get_dep_volume() {
    local project_name="$PROJECT_NAME"

    if [[ -f "package.json" ]]; then
        echo "${project_name}-node-modules:/workspace/node_modules"
    elif [[ -f "requirements.txt" ]] || [[ -f "pyproject.toml" ]]; then
        echo "${project_name}-venv:/workspace/.venv"
    elif [[ -f "Cargo.toml" ]]; then
        echo "${project_name}-target:/workspace/target"
    elif [[ -f "go.mod" ]]; then
        echo "${project_name}-gopath:/go"
    elif [[ -f "composer.json" ]]; then
        echo "${project_name}-vendor:/workspace/vendor"
    else
        echo ""
    fi
}

export DOCKERFILE
export IMAGE_NAME

export -f detect_safe_mode
export -f build_docker_image
export -f generate_dockerfile
export -f get_dep_volume